function testCreateObject(kind, name = invalid)
    return {}
end function

sub main()
    attrs = playbackAttributes("CODECS=" + Chr(34) + "avc1.4D401F,mp4a.40.2" + Chr(34) + ", FRAME-RATE=59.94, VIDEO=" + Chr(34) + "chunked" + Chr(34))
    check(attrs.CODECS = "avc1.4D401F,mp4a.40.2", "quoted codec commas remain one attribute")
    check(attrs["FRAME-RATE"] = "59.94", "spaced attributes preserve actual frame rate")
    q = Chr(34)
    playlist = "#EXTM3U" + Chr(10)
    playlist += "#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=" + q + "chunked" + q + ",NAME=" + q + "1080p60 (source)" + q + Chr(10)
    playlist += "#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=" + q + "720p30" + q + ",NAME=" + q + "720p" + q + Chr(10)
    playlist += "#EXT-X-STREAM-INF:BANDWIDTH=6000000,CODECS=" + q + "avc1.64002A,mp4a.40.2" + q + ",RESOLUTION=1920x1080,FRAME-RATE=59.94,VIDEO=" + q + "chunked" + q + Chr(10)
    playlist += "#EXT-X-TWITCH-INFO:EXTRA=1" + Chr(10) + Chr(10) + "https://cdn.example/source.m3u8" + Chr(13) + Chr(10)
    playlist += "#EXT-X-STREAM-INF:VIDEO=" + q + "480p30" + q + ",RESOLUTION=852x480,FRAME-RATE=30,BANDWIDTH=1400000" + Chr(10) + "/480.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:VIDEO=" + q + "720p30" + q + ",RESOLUTION=1280x720,FRAME-RATE=30,BANDWIDTH=2800000" + Chr(10) + "720.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:VIDEO=" + q + "720p60" + q + ",RESOLUTION=1280x720,FRAME-RATE=60" + Chr(10) + "//cdn.example/72060.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:RESOLUTION=640x360,FRAME-RATE=30" + Chr(10) + "360.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:BANDWIDTH=128000,VIDEO=" + q + "audio_only" + q + Chr(10) + "audio.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:RESOLUTION=3840x2160,CODECS=" + q + "hvc1.1.6,mp4a.40.2" + q + Chr(10) + "hevc.m3u8" + Chr(10)
    playlist += "#EXT-X-STREAM-INF:RESOLUTION=1280x720" + Chr(10) + "720.m3u8" + Chr(10)
    variants = parsePlaybackMaster(playlist, "https://usher.example/path/master.m3u8?token=x")
    check(variants.Count() = 5, "parser excludes audio, HEVC and duplicate video URLs")
    check(variants[0].name = "1080p60 (source)" and variants[0].frameRate = 60, "source preserves name and actual frame rate")
    check(variants[1].height = 720 and variants[1].frameRate = 60, "variants sorted by resolution then frame rate")
    check(variants[2].name = "720p", "media names matched by group despite intervening declarations")
    check(variants[2].url = "https://usher.example/path/720.m3u8", "relative URL uses master directory without query")
    check(variants[3].url = "https://usher.example/480.m3u8", "root-relative variant uses master host")
    check(variants[1].url = "https://cdn.example/72060.m3u8", "scheme-relative URL uses HTTPS")
    check(playbackAutoIndex(variants) = 2, "Auto starts at 720p30 rather than 60fps/source")
    check(playbackPreferenceIndex(variants, "1080p60 (source)") = 0, "explicit source selection stays available")
    check(playbackPreferenceIndex(variants, "missing") = 2, "unavailable preference falls back to safe Auto")
    check(playbackFallbackIndex(variants, 2, {"2": true}) = 3, "Auto falls back to 480p30")
    check(playbackFallbackIndex(variants, 3, {"2": true, "3": true}) = 4, "Auto then falls back to 360p30")
    check(playbackFallbackIndex(variants, 4, {"2": true, "3": true, "4": true}) = -1, "fallback exhausts ladder without retry loop")
    check(playbackAutoIndex([]) = -1, "empty playlist has no playable index")
    print "PASS HLS parsing, compatible Auto selection and finite fallback ladder"
end sub
